============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/james/projects/cs6223/our_proptest_data
plugins: hypothesis-6.112.2, timeout-2.3.1
collected 15 items

doc_and_code/mutants/statistics.median/mutant_1.py FFFFF                 [ 33%]
doc_and_code/mutants/statistics.median/mutant_2.py FFFFF                 [ 66%]
doc_and_code/mutants/statistics.median/mutant_3.py F.FFF                 [100%]

=================================== FAILURES ===================================
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants/statistics.median/mutant_1.py:6: exceptiongroup.ExceptionGroup: Hypothesis found 2 distinct failures. (2 sub-exceptions)
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants/statistics.median/mutant_1.py:21: assert 0 == (0 + 1)
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants/statistics.median/mutant_1.py:30: assert 1 == 0
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants/statistics.median/mutant_1.py:39: assert 0 is None
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants/statistics.median/mutant_1.py:48: assert 0 == -1
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants/statistics.median/mutant_2.py:13: assert 0.5 == (0 + 1)
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants/statistics.median/mutant_2.py:23: assert 0.5 == 0
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants/statistics.median/mutant_2.py:33: assert 0.5 == 1
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants/statistics.median/mutant_2.py:43: assert 0.5 == 0
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants/statistics.median/mutant_2.py:53: assert 0.0 == (1 / 4)
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants/statistics.median/mutant_3.py:6: hypothesis.errors.FailedHealthCheck: Tests run under @given should return None, but test_violation_of_statistics_median_1 returned 'No data' instead.
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants/statistics.median/mutant_3.py:22: hypothesis.errors.FailedHealthCheck: Tests run under @given should return None, but test_violation_of_statistics_median_3 returned 0 instead.
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants/statistics.median/mutant_3.py:30: hypothesis.errors.FailedHealthCheck: Tests run under @given should return None, but test_violation_of_statistics_median_4 returned 'Median is undefined' instead.
/home/james/projects/cs6223/our_proptest_data/doc_and_code/mutants/statistics.median/mutant_3.py:38: hypothesis.errors.FailedHealthCheck: Tests run under @given should return None, but test_violation_of_statistics_median_5 returned False instead.
=========================== short test summary info ============================
FAILED doc_and_code/mutants/statistics.median/mutant_1.py::test_violation_of_statistics_median_1
FAILED doc_and_code/mutants/statistics.median/mutant_1.py::test_violation_of_statistics_median_2
FAILED doc_and_code/mutants/statistics.median/mutant_1.py::test_violation_of_statistics_median_3
FAILED doc_and_code/mutants/statistics.median/mutant_1.py::test_violation_of_statistics_median_4
FAILED doc_and_code/mutants/statistics.median/mutant_1.py::test_violation_of_statistics_median_5
FAILED doc_and_code/mutants/statistics.median/mutant_2.py::test_violation_of_statistics_median_1
FAILED doc_and_code/mutants/statistics.median/mutant_2.py::test_violation_of_statistics_median_2
FAILED doc_and_code/mutants/statistics.median/mutant_2.py::test_violation_of_statistics_median_3
FAILED doc_and_code/mutants/statistics.median/mutant_2.py::test_violation_of_statistics_median_4
FAILED doc_and_code/mutants/statistics.median/mutant_2.py::test_violation_of_statistics_median_5
FAILED doc_and_code/mutants/statistics.median/mutant_3.py::test_violation_of_statistics_median_1
FAILED doc_and_code/mutants/statistics.median/mutant_3.py::test_violation_of_statistics_median_3
FAILED doc_and_code/mutants/statistics.median/mutant_3.py::test_violation_of_statistics_median_4
FAILED doc_and_code/mutants/statistics.median/mutant_3.py::test_violation_of_statistics_median_5
========================= 14 failed, 1 passed in 1.44s =========================
