============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/james/projects/cs6223/our_proptest_data
plugins: hypothesis-6.112.2, timeout-2.3.1
collected 5 items

mutants/statistics_variance/mutant_1.py F                                [ 20%]
mutants/statistics_variance/mutant_2.py F                                [ 40%]
mutants/statistics_variance/mutant_3.py F                                [ 60%]
mutants/statistics_variance/mutant_4.py F                                [ 80%]
mutants/statistics_variance/mutant_5.py F                                [100%]

=================================== FAILURES ===================================
/home/james/projects/cs6223/our_proptest_data/mutants/statistics_variance/mutant_1.py:5: exceptiongroup.ExceptionGroup: Hypothesis found 4 distinct failures. (4 sub-exceptions)
/home/james/projects/cs6223/our_proptest_data/mutants/statistics_variance/mutant_2.py:5: exceptiongroup.ExceptionGroup: Hypothesis found 5 distinct failures. (5 sub-exceptions)
/home/james/projects/cs6223/our_proptest_data/mutants/statistics_variance/mutant_3.py:5: NameError: name 'statistics' is not defined
/home/james/projects/cs6223/our_proptest_data/mutants/statistics_variance/mutant_4.py:5: exceptiongroup.ExceptionGroup: Hypothesis found 4 distinct failures. (4 sub-exceptions)
/home/james/projects/cs6223/our_proptest_data/mutants/statistics_variance/mutant_5.py:5: exceptiongroup.ExceptionGroup: Hypothesis found 4 distinct failures. (4 sub-exceptions)
=========================== short test summary info ============================
FAILED mutants/statistics_variance/mutant_1.py::test_violation_of_statistics_variance_property
FAILED mutants/statistics_variance/mutant_2.py::test_violation_of_statistics_variance_property
FAILED mutants/statistics_variance/mutant_3.py::test_violation_of_statistics_variance_property
FAILED mutants/statistics_variance/mutant_4.py::test_violation_of_statistics_variance_property
FAILED mutants/statistics_variance/mutant_5.py::test_violation_of_statistics_variance_property
============================== 5 failed in 2.38s ===============================
